language: ruby
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.10.6
notifications:
  webhooks:
    urls:
      - http://ce88348b.ngrok.io/travis
    on_success: always
    on_failure: always
    on_start: always
